package main

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/boshu2/agentops/cli/internal/formatter"
	"github.com/boshu2/agentops/cli/internal/search"
	"github.com/spf13/cobra"
)

type (
	constraintIndex     = search.ConstraintIndex
	constraintEntry     = search.ConstraintEntry
	constraintAppliesTo = search.ConstraintAppliesTo
	constraintDetector  = search.ConstraintDetector
)

var constraintCmd = &cobra.Command{
	Use:   "constraint",
	Short: "Manage compiled constraints",
	Long: `Manage constraints compiled from promoted findings.

Constraints are generated by hooks/finding-compiler.sh into
.agents/constraints/index.json. This command manages their lifecycle.

Subcommands:
  activate  Change a constraint from draft to active
  retire    Change a constraint from active to retired
  review    List constraints needing review (>90 days without citation)
  list      List all constraints with status`,
}

func init() {
	constraintCmd.GroupID = "core"
	rootCmd.AddCommand(constraintCmd)
	constraintCmd.AddCommand(constraintActivateCmd)
	constraintCmd.AddCommand(constraintRetireCmd)
	constraintCmd.AddCommand(constraintReviewCmd)
	constraintCmd.AddCommand(constraintListCmd)
}

func constraintIndexPath() string  { return search.ConstraintIndexPath() }
func constraintLockPath() string   { return search.ConstraintLockPath() }
func loadConstraintIndex() (*constraintIndex, error) {
	return search.LoadConstraintIndex()
}
func withConstraintLock(fn func() error) error { return search.WithConstraintLock(fn) }
func saveConstraintIndexUnlocked(idx *constraintIndex) error {
	return search.SaveConstraintIndexUnlocked(idx)
}
func saveConstraintIndex(idx *constraintIndex) error { return search.SaveConstraintIndex(idx) }
func findConstraint(idx *constraintIndex, id string) *constraintEntry {
	return search.FindConstraint(idx, id)
}

// printConstraintTable renders a slice of constraintEntry as a formatted table
// using formatter.Table with columns ID, STATUS, COMPILED, TITLE.
func printConstraintTable(entries []constraintEntry) {
	tbl := formatter.NewTable(os.Stdout, "ID", "STATUS", "COMPILED", "TITLE")
	tbl.SetMaxWidth(0, 30) // ID
	tbl.SetMaxWidth(2, 20) // COMPILED
	tbl.SetMaxWidth(3, 50) // TITLE
	for _, c := range entries {
		tbl.AddRow(c.ID, c.Status, c.CompiledAt, c.Title)
	}
	_ = tbl.Render()
}

// ----- activate -----

var constraintActivateCmd = &cobra.Command{
	Use:   "activate <id>",
	Short: "Change constraint status from draft to active",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id := args[0]
		var activated *constraintEntry
		if err := withConstraintLock(func() error {
			idx, err := loadConstraintIndex()
			if err != nil {
				return err
			}
			c := findConstraint(idx, id)
			if c == nil {
				return fmt.Errorf("constraint %q not found", id)
			}
			if c.Status != "draft" {
				return fmt.Errorf("constraint %q is %q, can only activate from draft", id, c.Status)
			}
			c.Status = "active"
			clone := *c
			activated = &clone
			return saveConstraintIndexUnlocked(idx)
		}); err != nil {
			return err
		}
		if GetOutput() == "json" {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(activated)
		}
		fmt.Printf("Constraint %q activated\n", id)
		return nil
	},
}

// ----- retire -----

var constraintRetireCmd = &cobra.Command{
	Use:   "retire <id>",
	Short: "Change constraint status from active to retired",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id := args[0]
		var retired *constraintEntry
		if err := withConstraintLock(func() error {
			idx, err := loadConstraintIndex()
			if err != nil {
				return err
			}
			c := findConstraint(idx, id)
			if c == nil {
				return fmt.Errorf("constraint %q not found", id)
			}
			if c.Status != "active" {
				return fmt.Errorf("constraint %q is %q, can only retire from active", id, c.Status)
			}
			c.Status = "retired"
			clone := *c
			retired = &clone
			return saveConstraintIndexUnlocked(idx)
		}); err != nil {
			return err
		}
		if GetOutput() == "json" {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(retired)
		}
		fmt.Printf("Constraint %q retired\n", id)
		return nil
	},
}

// ----- review -----

var constraintReviewCmd = &cobra.Command{
	Use:   "review",
	Short: "List constraints compiled >90 days ago without recent citation",
	RunE: func(cmd *cobra.Command, args []string) error {
		idx, err := loadConstraintIndex()
		if err != nil {
			return err
		}

		cutoff := time.Now().AddDate(0, 0, -90)
		stale := search.FilterStaleConstraints(idx.Constraints, cutoff)

		if GetOutput() == "json" {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(stale)
		}

		if len(stale) == 0 {
			fmt.Println("No constraints need review.")
			return nil
		}

		printConstraintTable(stale)
		fmt.Printf("\n%d constraint(s) need review (>90 days old)\n", len(stale))
		return nil
	},
}

// ----- list -----

var constraintListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all constraints with status",
	RunE: func(cmd *cobra.Command, args []string) error {
		idx, err := loadConstraintIndex()
		if err != nil {
			return err
		}

		if GetOutput() == "json" {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(idx.Constraints)
		}

		if len(idx.Constraints) == 0 {
			fmt.Println("No constraints found. Run hooks/constraint-compiler.sh to compile learnings.")
			return nil
		}

		printConstraintTable(idx.Constraints)
		fmt.Printf("\n%d constraint(s) total\n", len(idx.Constraints))
		return nil
	},
}
