package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/boshu2/agentops/cli/internal/formatter"
	"github.com/spf13/cobra"
)

// constraintIndex represents the .agents/constraints/index.json schema.
type constraintIndex struct {
	SchemaVersion int               `json:"schema_version"`
	Constraints   []constraintEntry `json:"constraints"`
}

// constraintEntry represents a single compiled constraint.
type constraintEntry struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Source     string `json:"source"`
	Status     string `json:"status"`
	CompiledAt string `json:"compiled_at"`
	File       string `json:"file"`
}

var constraintCmd = &cobra.Command{
	Use:   "constraint",
	Short: "Manage compiled constraints",
	Long: `Manage constraints compiled from high-scoring learnings.

Constraints are generated by hooks/constraint-compiler.sh from learnings
tagged "constraint" or "anti-pattern". This command manages their lifecycle.

Subcommands:
  activate  Change a constraint from draft to active
  retire    Change a constraint from active to retired
  review    List constraints needing review (>90 days without citation)
  list      List all constraints with status`,
}

func init() {
	constraintCmd.GroupID = "core"
	rootCmd.AddCommand(constraintCmd)
	constraintCmd.AddCommand(constraintActivateCmd)
	constraintCmd.AddCommand(constraintRetireCmd)
	constraintCmd.AddCommand(constraintReviewCmd)
	constraintCmd.AddCommand(constraintListCmd)
}

// constraintIndexPath returns the canonical path to the index file.
func constraintIndexPath() string {
	return filepath.Join(".agents", "constraints", "index.json")
}

// loadConstraintIndex reads and parses the constraint index.
func loadConstraintIndex() (*constraintIndex, error) {
	path := constraintIndexPath()
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("no constraints found — run constraint-compiler.sh first")
		}
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	var idx constraintIndex
	if err := json.Unmarshal(data, &idx); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	return &idx, nil
}

// saveConstraintIndex writes the constraint index back to disk.
func saveConstraintIndex(idx *constraintIndex) error {
	path := constraintIndexPath()
	data, err := json.MarshalIndent(idx, "", "  ")
	if err != nil {
		return fmt.Errorf("marshalling index: %w", err)
	}
	data = append(data, '\n')
	return os.WriteFile(path, data, 0o600)
}

// findConstraint locates a constraint by ID and returns its pointer.
func findConstraint(idx *constraintIndex, id string) *constraintEntry {
	for i := range idx.Constraints {
		if idx.Constraints[i].ID == id {
			return &idx.Constraints[i]
		}
	}
	return nil
}

// printConstraintTable renders a slice of constraintEntry as a formatted table
// using formatter.Table with columns ID, STATUS, COMPILED, TITLE.
func printConstraintTable(entries []constraintEntry) {
	tbl := formatter.NewTable(os.Stdout, "ID", "STATUS", "COMPILED", "TITLE")
	tbl.SetMaxWidth(0, 30)  // ID
	tbl.SetMaxWidth(2, 20)  // COMPILED
	tbl.SetMaxWidth(3, 50)  // TITLE
	for _, c := range entries {
		tbl.AddRow(c.ID, c.Status, c.CompiledAt, c.Title)
	}
	_ = tbl.Render()
}

// ----- activate -----

var constraintActivateCmd = &cobra.Command{
	Use:   "activate <id>",
	Short: "Change constraint status from draft to active",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id := args[0]
		idx, err := loadConstraintIndex()
		if err != nil {
			return err
		}
		c := findConstraint(idx, id)
		if c == nil {
			return fmt.Errorf("constraint %q not found", id)
		}
		if c.Status != "draft" {
			return fmt.Errorf("constraint %q is %q, can only activate from draft", id, c.Status)
		}
		c.Status = "active"
		if err := saveConstraintIndex(idx); err != nil {
			return err
		}
		if GetOutput() == "json" {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(c)
		}
		fmt.Printf("Constraint %q activated\n", id)
		return nil
	},
}

// ----- retire -----

var constraintRetireCmd = &cobra.Command{
	Use:   "retire <id>",
	Short: "Change constraint status from active to retired",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id := args[0]
		idx, err := loadConstraintIndex()
		if err != nil {
			return err
		}
		c := findConstraint(idx, id)
		if c == nil {
			return fmt.Errorf("constraint %q not found", id)
		}
		if c.Status != "active" {
			return fmt.Errorf("constraint %q is %q, can only retire from active", id, c.Status)
		}
		c.Status = "retired"
		if err := saveConstraintIndex(idx); err != nil {
			return err
		}
		if GetOutput() == "json" {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(c)
		}
		fmt.Printf("Constraint %q retired\n", id)
		return nil
	},
}

// ----- review -----

var constraintReviewCmd = &cobra.Command{
	Use:   "review",
	Short: "List constraints compiled >90 days ago without recent citation",
	RunE: func(cmd *cobra.Command, args []string) error {
		idx, err := loadConstraintIndex()
		if err != nil {
			return err
		}

		cutoff := time.Now().AddDate(0, 0, -90)
		stale := []constraintEntry{}

		for _, c := range idx.Constraints {
			if c.Status == "retired" {
				continue
			}
			compiled, parseErr := time.Parse(time.RFC3339, c.CompiledAt)
			if parseErr != nil {
				// Try date-only format
				compiled, parseErr = time.Parse("2006-01-02", c.CompiledAt)
				if parseErr != nil {
					continue
				}
			}
			if compiled.Before(cutoff) {
				stale = append(stale, c)
			}
		}

		if GetOutput() == "json" {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(stale)
		}

		if len(stale) == 0 {
			fmt.Println("No constraints need review.")
			return nil
		}

		printConstraintTable(stale)
		fmt.Printf("\n%d constraint(s) need review (>90 days old)\n", len(stale))
		return nil
	},
}

// ----- list -----

var constraintListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all constraints with status",
	RunE: func(cmd *cobra.Command, args []string) error {
		idx, err := loadConstraintIndex()
		if err != nil {
			return err
		}

		if GetOutput() == "json" {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			return enc.Encode(idx.Constraints)
		}

		if len(idx.Constraints) == 0 {
			fmt.Println("No constraints found. Run hooks/constraint-compiler.sh to compile learnings.")
			return nil
		}

		printConstraintTable(idx.Constraints)
		fmt.Printf("\n%d constraint(s) total\n", len(idx.Constraints))
		return nil
	},
}
