#!/usr/bin/env bash
set -euo pipefail

# Generate cli/docs/COMMANDS.md from ao --help output.
# Usage:
#   ./scripts/generate-cli-reference.sh          # Generate COMMANDS.md
#   ./scripts/generate-cli-reference.sh --check   # Check if committed version is current

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$REPO_ROOT/cli/docs/COMMANDS.md"
CHECK_MODE=false

if [[ "${1:-}" == "--check" ]]; then
  CHECK_MODE=true
fi

# Verify ao is available
if ! command -v ao &>/dev/null; then
  echo "ERROR: ao CLI not found in PATH. Build it first: cd cli && go build -o ao ." >&2
  exit 1
fi

generate() {
  local date
  date="$(date +%Y-%m-%d)"

  cat <<EOF
# ao CLI Reference

> Auto-generated by \`scripts/generate-cli-reference.sh\` on ${date}.
> Do not edit manually. Re-run the script to update.

EOF

  # Capture top-level help
  local top_help
  top_help="$(ao --help 2>&1)"

  # Global flags
  cat <<'EOF'
## Global Flags

EOF
  echo "$top_help" | sed -n '/^Flags:/,/^$/{ /^Flags:/d; /^$/d; p; }' | while IFS= read -r line; do
    echo "    $line"
  done
  echo ""

  # Extract command names from "Available Commands:" section
  local commands
  commands="$(echo "$top_help" | sed -n '/^Available Commands:/,/^$/{ /^Available Commands:/d; /^$/d; p; }' | awk '{print $1}' | grep -v '^$')"

  cat <<'EOF'
---

## Commands

EOF

  for cmd in $commands; do
    local cmd_help
    cmd_help="$(ao "$cmd" --help 2>&1 || true)"

    # First line is typically the short description
    local description
    description="$(echo "$cmd_help" | head -n1)"

    echo "### \`ao ${cmd}\`"
    echo ""
    echo "${description}"
    echo ""

    # Extract Usage line
    local usage
    usage="$(echo "$cmd_help" | grep -E '^Usage:' -A1 | tail -n1 | sed 's/^[[:space:]]*//' || true)"
    if [[ -n "$usage" ]]; then
      echo '```'
      echo "$usage"
      echo '```'
      echo ""
    fi

    # Extract flags (local flags section, skip if only -h/--help)
    local flags_block
    flags_block="$(echo "$cmd_help" | sed -n '/^Flags:/,/^$/{ /^Flags:/d; /^$/d; p; }' || true)"
    # Check if there are flags beyond just -h/--help
    local non_help_flags
    non_help_flags="$(echo "$flags_block" | grep -v '^\s*-h,' | grep -v '^\s*$' || true)"
    if [[ -n "$non_help_flags" ]]; then
      echo "**Flags:**"
      echo ""
      echo '```'
      echo "$flags_block"
      echo '```'
      echo ""
    fi

    # Check for subcommands
    local subcmds
    subcmds="$(echo "$cmd_help" | sed -n '/^Available Commands:/,/^$/{ /^Available Commands:/d; /^$/d; p; }' | awk '{print $1}' | grep -v '^$' || true)"
    if [[ -n "$subcmds" ]]; then
      echo "**Subcommands:**"
      echo ""
      for sub in $subcmds; do
        local sub_help
        sub_help="$(ao "$cmd" "$sub" --help 2>&1 || true)"
        local sub_desc
        sub_desc="$(echo "$sub_help" | head -n1)"
        echo "#### \`ao ${cmd} ${sub}\`"
        echo ""
        echo "${sub_desc}"
        echo ""

        local sub_usage
        sub_usage="$(echo "$sub_help" | grep -E '^Usage:' -A1 | tail -n1 | sed 's/^[[:space:]]*//' || true)"
        if [[ -n "$sub_usage" ]]; then
          echo '```'
          echo "$sub_usage"
          echo '```'
          echo ""
        fi

        local sub_flags
        sub_flags="$(echo "$sub_help" | sed -n '/^Flags:/,/^$/{ /^Flags:/d; /^$/d; p; }' || true)"
        local sub_non_help
        sub_non_help="$(echo "$sub_flags" | grep -v '^\s*-h,' | grep -v '^\s*$' || true)"
        if [[ -n "$sub_non_help" ]]; then
          echo "**Flags:**"
          echo ""
          echo '```'
          echo "$sub_flags"
          echo '```'
          echo ""
        fi
      done
    fi

    echo "---"
    echo ""
  done
}

if $CHECK_MODE; then
  tmpfile="$(mktemp)"
  trap 'rm -f "$tmpfile"' EXIT
  generate > "$tmpfile"
  if diff -q "$OUTPUT" "$tmpfile" &>/dev/null; then
    echo "cli/docs/COMMANDS.md is up to date."
    exit 0
  else
    echo "cli/docs/COMMANDS.md is out of date. Run: ./scripts/generate-cli-reference.sh" >&2
    diff -u "$OUTPUT" "$tmpfile" || true
    exit 1
  fi
fi

mkdir -p "$(dirname "$OUTPUT")"
generate > "$OUTPUT"
echo "Generated $OUTPUT"
