#!/usr/bin/env bats

setup() {
    REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
    SCRIPT="$REPO_ROOT/scripts/generate-index.sh"
    TMP_DIR="$(mktemp -d)"
    AGENTS_DIR="$TMP_DIR/.agents"

    mkdir -p "$AGENTS_DIR/learnings"
    printf '# Stable Learning\n' > "$AGENTS_DIR/learnings/stable.md"
}

teardown() {
    rm -rf "$TMP_DIR"
}

@test "generate-index emits byte-stable output without wall-clock footer" {
    run bash "$SCRIPT" "$AGENTS_DIR"
    [ "$status" -eq 0 ]

    run grep -F '_Generated by `scripts/generate-index.sh`._' "$AGENTS_DIR/INDEX.md"
    [ "$status" -eq 0 ]

    run grep -E '_Generated: [0-9]{4}-[0-9]{2}-[0-9]{2}|date -Iseconds' "$AGENTS_DIR/INDEX.md"
    [ "$status" -eq 1 ]

    first="$(<"$AGENTS_DIR/INDEX.md")"
    sleep 1

    run bash "$SCRIPT" "$AGENTS_DIR"
    [ "$status" -eq 0 ]
    second="$(<"$AGENTS_DIR/INDEX.md")"

    [ "$first" = "$second" ]
}
